version: "3.8"

services:
  database:
    image: mariadb:10.6
    container_name: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: rootpassword
      MARIADB_DATABASE: database_test
      MARIADB_USER: tuananhdev
      MARIADB_PASSWORD: 123456789
    ports:
      - "3308:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

  backend:
    image: tuananhdev911/spring-boot-app:latest # Đảm bảo bạn đã push image lên Docker Hub
    container_name: spring-boot-app
    restart: always
    ports:
      - "8082:8082"
    depends_on:
      - database
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://database:3308/database_test
      SPRING_DATASOURCE_USERNAME: tuananhdev
      SPRING_DATASOURCE_PASSWORD: 123456789

volumes:
  mariadb_data:
