version: "3.8"

services:
  app:
    build: .
    ports:
      - "8082:8082"
    environment:
      - SERVER_PORT=8082
      - SPRING_DATASOURCE_URL=jdbc:mariadb://host.docker.internal:3307/database_test
      - SPRING_DATASOURCE_USERNAME=tuananhdev
      - SPRING_DATASOURCE_PASSWORD=123456789
    depends_on:
      - mariadb
    restart: unless-stopped

  mariadb:
    image: mariadb:10.6
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=database_test
      - MYSQL_USER=tuananhdev
      - MYSQL_PASSWORD=123456789
    ports:
      - "3307:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  mariadb_data:
